services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db"]
      interval: 5s
      retries: 5
      timeout: 10s

  api:
    build:
      dockerfile: "dockerfile"
      context: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: "always"

volumes:
  postgres_data:
